# **2. CLASSEMENT SELON DES THEMES**

In [ ]:
from dotenv import load_dotenv
from transformers import AutoTokenizer, XLMRobertaForSequenceClassification, AutoModelForSequenceClassification, pipeline
import os
import pandas as pd
from huggingface_hub import login
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from mistralai import Mistral
import time

from utils import add_prefix, run_damo_xlm, run_facebook_bart, run_xlm_roberta_xnli, run_mdeberta_xnli, compare_models, get_topic_keywords, classify

load_dotenv()

In [4]:
# Chargement des themes depuis le fichier texte
with open("data/themes.txt", "r", encoding="utf-8") as f:
    themes = [line.strip() for line in f if line.strip()]

print(themes)

['distance avec les autres villes', 'types de population', 'esthétique de la ville', 'histoire de la toponymie urbaine', 'élement géomorphologique', 'périphérie de ville', 'porte', 'voirie', 'pouvoir', 'palais ; citadelle et château', 'mur et murailles', 'matériaux', 'infrastructure de services', 'eau potable et fontaine', 'pont', 'port et bateau', 'habitation et maison', 'marché', 'richesse de la ville ou du prince', 'impôts et taxes', 'espaces agricoles', 'artisanat', 'mosquée', 'église', 'synagogue', 'cimetière et tombes', 'monuments et vestiges', 'pyramide', 'jardin', 'climat', 'animaux', 'plantes et arbres']

In [5]:
# Chargement du dataframe exporté en fin de première partie
df_chunks = pd.read_excel('data/df_chunks_part1.xlsx')

## **2.1. Zero-shot-classifaction**

Les quatre modèles que nous utilisons pour la classification zero-shot reposent tous sur des architectures de type Transformer, mais présentent des différences liées à leurs bases pré-entraînées et à leurs objectifs spécifiques.
1. Le modèle `DAMO-NLP-SG/zero-shot-classify-SSTuning-XLM-R` est basé sur XLM-RoBERTa et optimisé pour le **multilingue**, avec un entraînement spécial pour la classification zero-shot, ce qui le rend adapté à des textes dans plusieurs langues.
2. Le modèle `facebook/bart-large-mnli` est une version fine-tunée du modèle BART, entraîné sur la tâche NLI (Natural Language Inference) en anglais, souvent utilisé en zero-shot grâce à sa capacité à comprendre des relations entre phrases, mais son multilinguisme est plus limité.
3. Le modèle `joeddav/xlm-roberta-large-xnli` est basé sur XLM-RoBERTa large et fine-tuné sur le dataset XNLI, une tâche NLI multilingue, ce qui pourrait être un bon choix pour le zero-shot multilingue, notamment sur des langues comme l’arabe ou l’hébreu.
4. Enfin, `MoritzLaurer/mDeBERTa-v3-base-mnli-xnli` est une variante récente de DeBERTa, fine-tunée sur **MNLI et XNLI**, combinant des améliorations architecturales (comme un meilleur décodage du contexte) avec un apprentissage sur des données multilingues, ce qui le rend performant en classification zero-shot dans plusieurs langues.

In [3]:
# Téléchargement pour DAMO XLM-R (zero-shot multilingue)
print("Téléchargement : DAMO-NLP-SG/zero-shot-classify-SSTuning-XLM-R")
AutoTokenizer.from_pretrained("DAMO-NLP-SG/zero-shot-classify-SSTuning-XLM-R")
AutoModelForSequenceClassification.from_pretrained("DAMO-NLP-SG/zero-shot-classify-SSTuning-XLM-R")

# Téléchargement pour Facebook BART Large MNLI
print("Téléchargement : facebook/bart-large-mnli")
pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Téléchargement pour XLM-RoBERTa Large XNLI
print("Téléchargement : joeddav/xlm-roberta-large-xnli")
pipeline("zero-shot-classification", model="joeddav/xlm-roberta-large-xnli")

# Téléchargement pour mDeBERTa v3 base XNLI
print("Téléchargement : MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")
pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")

Téléchargement : DAMO-NLP-SG/zero-shot-classify-SSTuning-XLM-R
Téléchargement : facebook/bart-large-mnli

Device set to use mps:0

Téléchargement : joeddav/xlm-roberta-large-xnli

Some weights of the model checkpoint at joeddav/xlm-roberta-large-xnli were not used when initializing XLMRobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use mps:0

Téléchargement : MoritzLaurer/mDeBERTa-v3-base-mnli-xnli

Device set to use mps:0

In [4]:
# Configuration
HF_API_KEY = os.getenv('HF_API_KEY')
login(token=HF_API_KEY)

models = {
    "XLM-R (DAMO)": run_damo_xlm,
    "Facebook BART": run_facebook_bart,
    "XLM-R XNLI": run_xlm_roberta_xnli,
    "mDeBERTa XNLI": run_mdeberta_xnli,
}

In [6]:
# Exécution
text = df_chunks.loc[553, 'CHUNK_MOTS']
df_comparaison = compare_models(text, themes, models)
df_comparaison = df_comparaison.style.apply(lambda x: ['background-color: yellow' if val in x.nlargest(4).values else '' for val in x])
print(text)
df_comparaison

Running model: XLM-R (DAMO)
Running model: Facebook BART

Device set to use cpu

Running model: XLM-R XNLI

Some weights of the model checkpoint at joeddav/xlm-roberta-large-xnli were not used when initializing XLMRobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

Running model: mDeBERTa XNLI

Device set to use cpu

testati sunt nobis redeunes, se numquam in plano fortius vidisse castrum: septem turres habet firmissimas testudinatas, insuper per girum duplici fossato et utroque murato cingitur habens antemurale.

> **Traduction en français du passage latin**: « Les nôtres, quand ils s'en revinrent de cette expédition, nous affirmèrent que, jamais, en terrain plat, ils n'avaient vu une citadelle plus puissante; elle possède sept tours très fortes et couvertes en dôme; en outre, sur tout son pourtour, elle est ceinte d'un double fossé, et chacun de ses fossés est défendu pat un mur ; en plus, elle possède un avant-mur. »

Les thèmes ici devrait être :
* palais ; citadelle et château ("ils n'avaient vu une citadelle plus puissante")
* mur et murailles ("elle est ceinte d'un double fossé, et chacun de ses fossés est défendu pat un mur ; en plus, elle possède un avant-mur")

Seul le modèle XLM-R XNLI, dont le score des 3 premiers thèmes les plus élevé correspond au thèmes que nous avons choisi. Toutefois, lorsque l'on regarde de plus prêts, il attribue le thème animaux avec un score de 98% ; or à aucun moment il est question d'animaux  dans ce chunks-là. Cela rend ainsi compliqué le choix de la limite de confiance à attriber

Essayons un autre façon de faire !

## **2.2. BERTopic**

In [19]:
topic_list = [
    ["distance", "ville"],
    ["type", "population"],
    ["esthétique", "ville"],
    ["histoire", "ville","toponymie"],
    ["périphérie","ville"],
    ["porte","ville"],
    ["voirie","ville"],
    ["pouvoir","ville"],
    ["palais","citadelle","chateau"],
    ["mur","murailles"],
    ["matériaux","ville"],
    ["service","ville", "infrastructure"],
    ["eau"],
    ["fontaine"],
    ["pont"],
    ["habitation","maison"],
    ["port","bateau"],
    ["marché"],
    ["richesse","ville","prince"],
    ["impôts","taxes"],
    ["agriculture"],
    ["artisanat"],
    ["mosquée"],
    ["église"],
    ["synagogue"],
    ["cimetière","tombes"],
    ["monuments","antiquités"],
    ["jardin"],
    ["climat"],
    ["animaux"],
    ["plantes","arbres"],
    ["pyramide"],
    ["montagne", "fleuve","relief","mer","plaine"]
]

In [8]:
classification_bertopic_model= SentenceTransformer('sentence-transformers/LaBSE')

In [9]:
topic_model = BERTopic(embedding_model=classification_bertopic_model,
                       seed_topic_list=topic_list,
                       calculate_probabilities=True,
                       verbose=True)

In [10]:
topics, probs = topic_model.fit_transform(df_chunks['CHUNK_MOTS'])

2025-08-30 12:36:07,761 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 20/20 [00:25<00:00,  1.26s/it]
2025-08-30 12:36:33,280 - BERTopic - Embedding - Completed ✓
2025-08-30 12:36:33,293 - BERTopic - Guided - Find embeddings highly related to seeded topics.
Batches: 100%|██████████| 2/2 [00:04<00:00,  2.03s/it]
2025-08-30 12:36:37,610 - BERTopic - Guided - Completed ✓
2025-08-30 12:36:37,612 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-08-30 12:36:49,454 - BERTopic - Dimensionality - Completed ✓
2025-08-30 12:36:49,480 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-08-30 12:36:49,776 - BERTopic - Cluster - Completed ✓
2025-08-30 12:36:49,886 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-08-30 12:36:50,127 - BERTopic - Representation - Completed ✓

In [11]:
# Utilisation d'une fonction pour récupérer les mots-clés des seed topics correspondants

multi_results = get_topic_keywords(probs, topic_list, threshold=0.01)

In [12]:
chunks = df_chunks['CHUNK_MOTS'].tolist()

In [13]:
for result in multi_results:
    chunk_id = result['chunk_id']
    print(f"\nChunk {chunk_id}: '{chunks[chunk_id][:100]}...'")

    for topic_info in result['detected_topics']:
        keywords = topic_info['keywords']
        prob = topic_info['probability']
        print(f"  - {keywords} : {prob:.2%}")

Chunk 0: 'الغسطاط تعرف بباب اليون وهو الموضع المعروف بالقصر فلما افتح عمرو بن العاص باب اليون فى خلافة عمر بن ...'
  - ['distance', 'ville'] : 53.75%
  - ['type', 'population'] : 4.35%
  - ['esthétique', 'ville'] : 2.97%
  - ['histoire', 'ville', 'toponymie'] : 2.66%
  - ['périphérie', 'ville'] : 2.97%
  - ['porte', 'ville'] : 3.76%
  - ['voirie', 'ville'] : 4.69%
  - ['pouvoir', 'ville'] : 7.02%
  - ['palais', 'citadelle', 'chateau'] : 2.99%
  - ['mur', 'murailles'] : 6.31%
  - ['matériaux', 'ville'] : 2.48%
  - ['service', 'ville', 'infrastructure'] : 3.58%

Chunk 1: 'عمرو بن العاص مسجد جامعها ودار امارتها المعروفة بدار الرمل وجعل الاسواق محيطة بالمسجد لجامع فى الجان...'
  - ['distance', 'ville'] : 40.61%
  - ['type', 'population'] : 5.79%
  - ['esthétique', 'ville'] : 3.70%
  - ['histoire', 'ville', 'toponymie'] : 3.41%
  - ['périphérie', 'ville'] : 3.70%
  - ['porte', 'ville'] : 4.93%
  - ['voirie', 'ville'] : 6.03%
  - ['pouvoir', 'ville'] : 6.87%
  - ['palais', 'citadelle', 'chateau'] : 3.71%
  - ['mur', 'murailles'] : 8.10%
  - ['matériaux', 'ville'] : 3.09%
  - ['service', 'ville', 'infrastructure'] : 4.68%

Chunk 2: 'واسكنه قوما وكتب الى عمر بن الخطاب بذلك فكتب اليه لا تجعل بينى وبين المسلمين ماء, وافتتح عمرو كور مص...'
  - ['distance', 'ville'] : 100.00%

Chunk 3: 'لان لكل كورة مدينة مخصوصة بأمر من الامور من مدن الصعيد وكورها مدينة منف وهى مدينة قائمة" خراب يقول ا...'
  - ['distance', 'ville'] : 5.75%
  - ['type', 'population'] : 16.95%
  - ['esthétique', 'ville'] : 3.25%
  - ['histoire', 'ville', 'toponymie'] : 5.31%
  - ['périphérie', 'ville'] : 4.87%
  - ['porte', 'ville'] : 8.18%
  - ['voirie', 'ville'] : 4.71%
  - ['pouvoir', 'ville'] : 3.45%
  - ['palais', 'citadelle', 'chateau'] : 4.36%
  - ['mur', 'murailles'] : 5.82%
  - ['matériaux', 'ville'] : 4.16%
  - ['service', 'ville', 'infrastructure'] : 6.25%

Chunk 4: 'ومدينة القيس وبها تعل الثياب القيسية والأكسية الصوف الجياد ومدينة المهنسا وبها تعمل الستور المهنسية ...'
  - ['distance', 'ville'] : 4.68%
  - ['type', 'population'] : 12.78%
  - ['esthétique', 'ville'] : 2.61%
  - ['histoire', 'ville', 'toponymie'] : 3.75%
  - ['périphérie', 'ville'] : 4.48%
  - ['porte', 'ville'] : 5.96%
  - ['voirie', 'ville'] : 4.71%
  - ['pouvoir', 'ville'] : 2.70%
  - ['palais', 'citadelle', 'chateau'] : 4.11%
  - ['mur', 'murailles'] : 4.43%
  - ['matériaux', 'ville'] : 3.41%
  - ['service', 'ville', 'infrastructure'] : 7.09%

Chunk 5: 'فى لجانب الشرقى من النيل ومدينة الأشمونين وبها فرهة الحيل والدواب والبغال وهى من مدن مصر العظام ومدي...'
  - ['distance', 'ville'] : 5.04%
  - ['type', 'population'] : 12.20%
  - ['esthétique', 'ville'] : 3.30%
  - ['histoire', 'ville', 'toponymie'] : 6.13%
  - ['périphérie', 'ville'] : 6.93%
  - ['porte', 'ville'] : 25.35%
  - ['voirie', 'ville'] : 4.43%
  - ['pouvoir', 'ville'] : 3.25%
  - ['palais', 'citadelle', 'chateau'] : 5.04%
  - ['mur', 'murailles'] : 6.47%
  - ['matériaux', 'ville'] : 5.29%
  - ['service', 'ville', 'infrastructure'] : 6.69%

Chunk 6: 'ولهما ساحل وبها يعمل الفرش القطوع والجلود الاخميمية والدير المعروف بدير بو شنودة ويقال ان فيه قبر رج...'
  - ['distance', 'ville'] : 7.22%
  - ['type', 'population'] : 11.20%
  - ['esthétique', 'ville'] : 3.73%
  - ['histoire', 'ville', 'toponymie'] : 5.78%
  - ['périphérie', 'ville'] : 9.07%
  - ['porte', 'ville'] : 14.83%
  - ['voirie', 'ville'] : 5.77%
  - ['pouvoir', 'ville'] : 4.18%
  - ['palais', 'citadelle', 'chateau'] : 6.58%
  - ['mur', 'murailles'] : 8.09%
  - ['matériaux', 'ville'] : 5.73%
  - ['service', 'ville', 'infrastructure'] : 8.15%

Chunk 7: 'ومن عجائب البلدان الهرمان ة بمصر سمك كل واحد منهما اربع مائة ذراع مكتوب عليهماء بالمسند كل سحر وكل ع...'
  - ['distance', 'ville'] : 4.21%
  - ['type', 'population'] : 4.86%
  - ['esthétique', 'ville'] : 4.96%
  - ['histoire', 'ville', 'toponymie'] : 2.87%
  - ['périphérie', 'ville'] : 3.89%
  - ['porte', 'ville'] : 3.73%
  - ['voirie', 'ville'] : 7.51%
  - ['pouvoir', 'ville'] : 2.96%
  - ['palais', 'citadelle', 'chateau'] : 5.58%
  - ['mur', 'murailles'] : 5.14%
  - ['matériaux', 'ville'] : 3.30%
  - ['service', 'ville', 'infrastructure'] : 5.57%

Chunk 8: 'لها الرعادة من مسها وجد خدرا في كفه ويده وذراعه ما دامت حية فان صبر ازداد ذلك حتى ترتعد يده وعضده وي...'
  - ['distance', 'ville'] : 2.89%
  - ['type', 'population'] : 4.04%
  - ['esthétique', 'ville'] : 3.79%
  - ['histoire', 'ville', 'toponymie'] : 2.93%
  - ['périphérie', 'ville'] : 5.08%
  - ['porte', 'ville'] : 3.47%
  - ['voirie', 'ville'] : 4.24%
  - ['pouvoir', 'ville'] : 2.30%
  - ['palais', 'citadelle', 'chateau'] : 17.82%
  - ['mur', 'murailles'] : 3.71%
  - ['matériaux', 'ville'] : 4.86%
  - ['service', 'ville', 'infrastructure'] : 4.62%

Chunk 9: 'و فوضع احد طرفيها على هذه الشبكة وامسك الطرف الآخر بيده خدرت يده وفى النيل ايضا حيوان يقال له التمسا...'
  - ['distance', 'ville'] : 3.15%
  - ['type', 'population'] : 4.63%
  - ['esthétique', 'ville'] : 3.69%
  - ['histoire', 'ville', 'toponymie'] : 3.16%
  - ['périphérie', 'ville'] : 6.48%
  - ['porte', 'ville'] : 4.00%
  - ['voirie', 'ville'] : 4.46%
  - ['pouvoir', 'ville'] : 2.46%
  - ['palais', 'citadelle', 'chateau'] : 38.43%
  - ['mur', 'murailles'] : 4.01%
  - ['matériaux', 'ville'] : 5.48%
  - ['service', 'ville', 'infrastructure'] : 4.95%

Chunk 10: 'من دنا الى الشط وتأكل الناس خاصة وسائر الحيوان وهي كثيرة مفرطة الكثرة في بلد من بلدان مصر يقال له ال...'
  - ['palais', 'citadelle', 'chateau'] : 100.00%

Chunk 11: 'يقربها تمساح بنة والناس منه آمنون فان وقع منها الى ذلك الموضع ايام المد تمساح بقى منقلناه على ظهره ح...'
  - ['distance', 'ville'] : 4.44%
  - ['type', 'population'] : 6.20%
  - ['esthétique', 'ville'] : 2.92%
  - ['histoire', 'ville', 'toponymie'] : 3.68%
  - ['périphérie', 'ville'] : 9.05%
  - ['porte', 'ville'] : 6.91%
  - ['voirie', 'ville'] : 4.33%
  - ['pouvoir', 'ville'] : 2.94%
  - ['palais', 'citadelle', 'chateau'] : 9.23%
  - ['mur', 'murailles'] : 5.82%
  - ['matériaux', 'ville'] : 5.41%
  - ['service', 'ville', 'infrastructure'] : 6.11%

Chunk 12: 'وكذلك الحال في فسطاط مصر من فوق الفسطاط باميال الى اسفل منه باميال نحو عشرة فانها بين هذين الموضعين ...'
  - ['distance', 'ville'] : 3.51%
  - ['type', 'population'] : 8.55%
  - ['esthétique', 'ville'] : 3.20%
  - ['histoire', 'ville', 'toponymie'] : 8.38%
  - ['périphérie', 'ville'] : 6.04%
  - ['porte', 'ville'] : 33.08%
  - ['voirie', 'ville'] : 3.37%
  - ['pouvoir', 'ville'] : 2.55%
  - ['palais', 'citadelle', 'chateau'] : 4.48%
  - ['mur', 'murailles'] : 5.29%
  - ['matériaux', 'ville'] : 6.57%
  - ['service', 'ville', 'infrastructure'] : 5.11%

Chunk 13: 'من رمية يريان من فرسخ واكثر وتعرفان بالهرمين فيهما كان يجمع الطعام ايام يوسف النبي صلعم وهذا الموضع ...'
  - ['distance', 'ville'] : 5.67%
  - ['type', 'population'] : 5.70%
  - ['esthétique', 'ville'] : 3.17%
  - ['histoire', 'ville', 'toponymie'] : 3.70%
  - ['périphérie', 'ville'] : 4.21%
  - ['porte', 'ville'] : 7.36%
  - ['voirie', 'ville'] : 3.70%
  - ['pouvoir', 'ville'] : 3.57%
  - ['palais', 'citadelle', 'chateau'] : 3.73%
  - ['mur', 'murailles'] : 15.96%
  - ['matériaux', 'ville'] : 3.61%
  - ['service', 'ville', 'infrastructure'] : 4.07%

Chunk 14: 'وان بيت مال مصر في المسجد الجامع قدام المنبر وهو منفصل من سطوح المسجد لا يتصل بشيء منها وهذا مرفوع ب...'
  - ['distance', 'ville'] : 7.04%
  - ['type', 'population'] : 6.26%
  - ['esthétique', 'ville'] : 8.18%
  - ['histoire', 'ville', 'toponymie'] : 4.90%
  - ['périphérie', 'ville'] : 4.15%
  - ['porte', 'ville'] : 5.75%
  - ['voirie', 'ville'] : 6.21%
  - ['pouvoir', 'ville'] : 5.01%
  - ['palais', 'citadelle', 'chateau'] : 4.74%
  - ['mur', 'murailles'] : 25.32%
  - ['matériaux', 'ville'] : 4.17%
  - ['service', 'ville', 'infrastructure'] : 4.98%

Chunk 15: 'سطح المسجد فاذا خرجوا ردوا القنطرة وعليها باب حديد واقفال واذا صلوا العشاء الآخرة أخرج الناس كلهم من...'
  - ['distance', 'ville'] : 6.66%
  - ['type', 'population'] : 7.23%
  - ['esthétique', 'ville'] : 8.11%
  - ['histoire', 'ville', 'toponymie'] : 5.62%
  - ['périphérie', 'ville'] : 4.32%
  - ['porte', 'ville'] : 6.43%
  - ['voirie', 'ville'] : 6.01%
  - ['pouvoir', 'ville'] : 4.60%
  - ['palais', 'citadelle', 'chateau'] : 4.79%
  - ['mur', 'murailles'] : 25.75%
  - ['matériaux', 'ville'] : 4.44%
  - ['service', 'ville', 'infrastructure'] : 5.18%

Chunk 16: 'وهناك بساتينهم وضياعهم ومتنزهاتهم وقد عقد على النيل مثل جسر بغداد فعبر عليه اليها وقد اتخذت علامات ت...'
  - ['distance', 'ville'] : 4.74%
  - ['type', 'population'] : 6.00%
  - ['esthétique', 'ville'] : 2.93%
  - ['histoire', 'ville', 'toponymie'] : 3.78%
  - ['périphérie', 'ville'] : 13.28%
  - ['porte', 'ville'] : 8.79%
  - ['voirie', 'ville'] : 4.62%
  - ['pouvoir', 'ville'] : 2.99%
  - ['palais', 'citadelle', 'chateau'] : 7.97%
  - ['mur', 'murailles'] : 5.82%
  - ['matériaux', 'ville'] : 5.18%
  - ['service', 'ville', 'infrastructure'] : 6.82%

Chunk 17: 'الى المسجد الجامع بأيديهم الرياحين ويقفون على حلقة حلقة ويرمون بما معهم من م الرياحين اليهم وينادون ...'
  - ['distance', 'ville'] : 4.53%
  - ['type', 'population'] : 5.39%
  - ['esthétique', 'ville'] : 2.65%
  - ['histoire', 'ville', 'toponymie'] : 2.97%
  - ['périphérie', 'ville'] : 8.32%
  - ['porte', 'ville'] : 6.08%
  - ['voirie', 'ville'] : 4.49%
  - ['pouvoir', 'ville'] : 2.72%
  - ['palais', 'citadelle', 'chateau'] : 7.25%
  - ['mur', 'murailles'] : 5.36%
  - ['matériaux', 'ville'] : 4.03%
  - ['service', 'ville', 'infrastructure'] : 5.96%

Chunk 18: 'عل ارضيه فغرقها حتى يختلفوا الى القرى في الزواريق فاذا نضب ذلك الماء زرعوا أرضيهم فيبلغ خراجهم الفى ...'
  - ['distance', 'ville'] : 5.52%
  - ['type', 'population'] : 6.89%
  - ['esthétique', 'ville'] : 3.08%
  - ['histoire', 'ville', 'toponymie'] : 3.89%
  - ['périphérie', 'ville'] : 8.62%
  - ['porte', 'ville'] : 8.02%
  - ['voirie', 'ville'] : 4.87%
  - ['pouvoir', 'ville'] : 3.34%
  - ['palais', 'citadelle', 'chateau'] : 7.43%
  - ['mur', 'murailles'] : 6.88%
  - ['matériaux', 'ville'] : 5.00%
  - ['service', 'ville', 'infrastructure'] : 6.61%

Chunk 19: 'والثالثة فسطاط مصر كان تمصير عمرو ابن العاص فسطاط مصر سنة ٢٠ وكان مسيره اليها وحروبه مع اهلها سنة 19...'
  - ['distance', 'ville'] : 100.00%

Chunk 20: 'يعرف بقصر الشمع بابلون وقيل اليونة فسماها المسلمون فسطاطا لأنهم قالوا هذا فسطاط القوم ومجمعهم...'
  - ['distance', 'ville'] : 49.00%
  - ['type', 'population'] : 5.16%
  - ['esthétique', 'ville'] : 3.30%
  - ['histoire', 'ville', 'toponymie'] : 3.03%
  - ['périphérie', 'ville'] : 3.42%
  - ['porte', 'ville'] : 4.34%
  - ['voirie', 'ville'] : 5.43%
  - ['pouvoir', 'ville'] : 7.34%
  - ['palais', 'citadelle', 'chateau'] : 3.42%
  - ['mur', 'murailles'] : 6.87%
  - ['matériaux', 'ville'] : 2.82%
  - ['service', 'ville', 'infrastructure'] : 4.16%

Chunk 21: 'ومن صفات مدنها وبقاعها أن مدينتها العظمى تسمى النطاط وفى على شمال النيل لأنه يجرى فى نحوها بين المشر...'
  - ['distance', 'ville'] : 4.34%
  - ['type', 'population'] : 12.24%
  - ['esthétique', 'ville'] : 3.26%
  - ['histoire', 'ville', 'toponymie'] : 7.06%
  - ['périphérie', 'ville'] : 7.26%
  - ['porte', 'ville'] : 29.27%
  - ['voirie', 'ville'] : 4.09%
  - ['pouvoir', 'ville'] : 2.96%
  - ['palais', 'citadelle', 'chateau'] : 5.07%
  - ['mur', 'murailles'] : 5.83%
  - ['matériaux', 'ville'] : 5.89%
  - ['service', 'ville', 'infrastructure'] : 6.60%

Chunk 22: 'الجزيرة على جسر آخر الى القسم الثانى كالجسر الأول الى أبية جليلة ومساكن على الشط الثالث تعرف بالجيزة...'
  - ['distance', 'ville'] : 3.84%
  - ['type', 'population'] : 9.47%
  - ['esthétique', 'ville'] : 3.55%
  - ['histoire', 'ville', 'toponymie'] : 6.19%
  - ['périphérie', 'ville'] : 3.48%
  - ['porte', 'ville'] : 8.70%
  - ['voirie', 'ville'] : 3.32%
  - ['pouvoir', 'ville'] : 2.57%
  - ['palais', 'citadelle', 'chateau'] : 3.16%
  - ['mur', 'murailles'] : 6.61%
  - ['matériaux', 'ville'] : 3.74%
  - ['service', 'ville', 'infrastructure'] : 4.11%

Chunk 23: 'والفسطاط مدينة كيرة نحو ثلث بغداذ ومقدارها نحو فرسح على غاية المارة والخصب والطيبة واللذة ذات رحاب ف...'
  - ['type', 'population'] : 100.00%

Chunk 24: 'ذلك فى وقتنا هذا وقد باد أكثرها بظاهر المعافر وفى سبخة الأرض غير نقية التربة...'
  - ['distance', 'ville'] : 3.43%
  - ['type', 'population'] : 6.19%
  - ['esthétique', 'ville'] : 2.65%
  - ['histoire', 'ville', 'toponymie'] : 3.96%
  - ['périphérie', 'ville'] : 8.57%
  - ['porte', 'ville'] : 6.92%
  - ['voirie', 'ville'] : 3.75%
  - ['pouvoir', 'ville'] : 2.37%
  - ['palais', 'citadelle', 'chateau'] : 8.14%
  - ['mur', 'murailles'] : 4.46%
  - ['matériaux', 'ville'] : 6.00%
  - ['service', 'ville', 'infrastructure'] : 6.62%

Chunk 25: 'والدار تكون بها طبقات سبعا وستا وخمس طبقات وربما سكن فى الدار المائنان من الناس, وبالفسطاط دار تعرف ...'
  - ['distance', 'ville'] : 4.88%
  - ['type', 'population'] : 3.23%
  - ['esthétique', 'ville'] : 2.60%
  - ['histoire', 'ville', 'toponymie'] : 1.79%
  - ['périphérie', 'ville'] : 1.95%
  - ['porte', 'ville'] : 2.37%
  - ['voirie', 'ville'] : 4.76%
  - ['pouvoir', 'ville'] : 2.50%
  - ['palais', 'citadelle', 'chateau'] : 2.20%
  - ['mur', 'murailles'] : 3.82%
  - ['matériaux', 'ville'] : 1.67%
  - ['service', 'ville', 'infrastructure'] : 2.88%

Chunk 26: 'وبها سجدان لصلاة الجمعة بنى أحدها عمرو بن العاص فى وسط الأسواق والآخر بأعلى الموقف بناء أبو العباس أ...'
  - ['distance', 'ville'] : 100.00%

Chunk 27: 'وقد استحدثت المغاربة بظاهر مصر مدينة سمتها القاهرة استحدثها جوهر صاحب أهل المغرب عند دخوله الى مصر ل...'
  - ['distance', 'ville'] : 9.82%
  - ['type', 'population'] : 15.26%
  - ['esthétique', 'ville'] : 4.69%
  - ['histoire', 'ville', 'toponymie'] : 6.40%
  - ['périphérie', 'ville'] : 5.13%
  - ['porte', 'ville'] : 7.91%
  - ['voirie', 'ville'] : 5.89%
  - ['pouvoir', 'ville'] : 5.44%
  - ['palais', 'citadelle', 'chateau'] : 5.16%
  - ['mur', 'murailles'] : 8.53%
  - ['matériaux', 'ville'] : 4.83%
  - ['service', 'ville', 'infrastructure'] : 6.25%

Chunk 28: 'وبها ديوان مصر ومجد جامع حسن نظيف غزير القوام والمؤذنين وقد ابتنت بعض نساء أهل المغرب جامعا آخر بالق...'
  - ['distance', 'ville'] : 12.77%
  - ['type', 'population'] : 6.44%
  - ['esthétique', 'ville'] : 3.93%
  - ['histoire', 'ville', 'toponymie'] : 3.78%
  - ['périphérie', 'ville'] : 3.35%
  - ['porte', 'ville'] : 4.73%
  - ['voirie', 'ville'] : 4.97%
  - ['pouvoir', 'ville'] : 5.32%
  - ['palais', 'citadelle', 'chateau'] : 3.57%
  - ['mur', 'murailles'] : 7.60%
  - ['matériaux', 'ville'] : 3.13%
  - ['service', 'ville', 'infrastructure'] : 4.23%

Chunk 29: 'ويصر نخيل كثيرة وبساتين وأجنة صالحة وتمتد زروعهم بما النيل من حد اسوان الى حد الإسكندرية والباطن ويق...'
  - ['distance', 'ville'] : 3.41%
  - ['type', 'population'] : 5.84%
  - ['esthétique', 'ville'] : 2.73%
  - ['histoire', 'ville', 'toponymie'] : 3.85%
  - ['périphérie', 'ville'] : 24.65%
  - ['porte', 'ville'] : 7.11%
  - ['voirie', 'ville'] : 4.00%
  - ['pouvoir', 'ville'] : 2.39%
  - ['palais', 'citadelle', 'chateau'] : 11.17%
  - ['mur', 'murailles'] : 4.15%
  - ['matériaux', 'ville'] : 6.56%
  - ['service', 'ville', 'infrastructure'] : 7.27%

Chunk 30: 'مصر مدينة يجرى فيها الماء من غير حاجة الى زيادة النيل إلا الفيوم والفيوم اسم الإقليم وبالفيوم مدينة ...'
  - ['distance', 'ville'] : 6.24%
  - ['type', 'population'] : 8.78%
  - ['esthétique', 'ville'] : 3.57%
  - ['histoire', 'ville', 'toponymie'] : 5.46%
  - ['périphérie', 'ville'] : 9.68%
  - ['porte', 'ville'] : 19.83%
  - ['voirie', 'ville'] : 4.97%
  - ['pouvoir', 'ville'] : 3.88%
  - ['palais', 'citadelle', 'chateau'] : 6.39%
  - ['mur', 'murailles'] : 8.82%
  - ['matériaux', 'ville'] : 5.88%
  - ['service', 'ville', 'infrastructure'] : 6.83%

Chunk 31: 'ذكر صقلية وأما صقلية فجزيرة طولها سبعة أيام في أربعة أيام والغالب عليها الجبال والقلاع والحصون وجميع...'
  - ['distance', 'ville'] : 4.29%
  - ['type', 'population'] : 29.26%
  - ['esthétique', 'ville'] : 3.36%
  - ['histoire', 'ville', 'toponymie'] : 8.17%
  - ['périphérie', 'ville'] : 5.70%
  - ['porte', 'ville'] : 12.20%
  - ['voirie', 'ville'] : 4.07%
  - ['pouvoir', 'ville'] : 2.92%
  - ['palais', 'citadelle', 'chateau'] : 4.79%
  - ['mur', 'murailles'] : 5.24%
  - ['matériaux', 'ville'] : 5.47%
  - ['service', 'ville', 'infrastructure'] : 6.42%

Chunk 32: 'المدينة الكبرى التي تسمى بلرم عليها سور من حجارة مانع شامخ يسكنها التجر وفيها مسجد الجامع الاكبر وكا...'
  - ['distance', 'ville'] : 13.14%
  - ['type', 'population'] : 5.93%
  - ['esthétique', 'ville'] : 3.63%
  - ['histoire', 'ville', 'toponymie'] : 3.73%
  - ['périphérie', 'ville'] : 3.30%
  - ['porte', 'ville'] : 4.89%
  - ['voirie', 'ville'] : 4.25%
  - ['pouvoir', 'ville'] : 5.69%
  - ['palais', 'citadelle', 'chateau'] : 3.33%
  - ['mur', 'murailles'] : 8.33%
  - ['matériaux', 'ville'] : 3.06%
  - ['service', 'ville', 'infrastructure'] : 3.85%

Chunk 33: 'لما شاهدت اليونانية عليه من أكباره واعظامه قال والسبب في تعليقة بين السماء والارض ما كان الناس يلاقو...'
  - ['distance', 'ville'] : 12.15%
  - ['type', 'population'] : 6.89%
  - ['esthétique', 'ville'] : 5.95%
  - ['histoire', 'ville', 'toponymie'] : 4.96%
  - ['périphérie', 'ville'] : 4.60%
  - ['porte', 'ville'] : 5.73%
  - ['voirie', 'ville'] : 6.43%
  - ['pouvoir', 'ville'] : 10.82%
  - ['palais', 'citadelle', 'chateau'] : 5.32%
  - ['mur', 'murailles'] : 14.09%
  - ['matériaux', 'ville'] : 4.56%
  - ['service', 'ville', 'infrastructure'] : 5.28%

Chunk 34: 'تعرف بالخالصة ذات سور ايضا من حجارة وليس كالسور الاول يسكنها السلطان واتباعه وليس فيها أسواق ولا فنا...'
  - ['type', 'population'] : 100.00%

Chunk 35: 'أعمر من المدينتين اللتين ذكرتهما وأجل ومرسى البحر بها وبها عيون جارية بينها وبين المدينة ومياه كالحد...'
  - ['distance', 'ville'] : 6.93%
  - ['type', 'population'] : 10.16%
  - ['esthétique', 'ville'] : 3.69%
  - ['histoire', 'ville', 'toponymie'] : 5.61%
  - ['périphérie', 'ville'] : 9.89%
  - ['porte', 'ville'] : 15.16%
  - ['voirie', 'ville'] : 5.57%
  - ['pouvoir', 'ville'] : 4.09%
  - ['palais', 'citadelle', 'chateau'] : 6.95%
  - ['mur', 'murailles'] : 8.45%
  - ['matériaux', 'ville'] : 5.97%
  - ['service', 'ville', 'infrastructure'] : 7.88%

Chunk 36: 'واجنتهم غير منتفعة به والحارة وهى حارة كبيرة تقارب حارة المسجد وليس بينهما فرق ولا فاصلة ولا على حار...'
  - ['distance', 'ville'] : 6.32%
  - ['type', 'population'] : 15.24%
  - ['esthétique', 'ville'] : 3.74%
  - ['histoire', 'ville', 'toponymie'] : 4.49%
  - ['périphérie', 'ville'] : 4.12%
  - ['porte', 'ville'] : 5.58%
  - ['voirie', 'ville'] : 6.22%
  - ['pouvoir', 'ville'] : 3.63%
  - ['palais', 'citadelle', 'chateau'] : 4.40%
  - ['mur', 'murailles'] : 5.57%
  - ['matériaux', 'ville'] : 3.71%
  - ['service', 'ville', 'infrastructure'] : 6.67%

Chunk 37: 'على اختلافهم وفي داخل البلد للقصابين فوق الخمسين وماية حانوت لبيع اللحم والقليل منهم هناك وهذا يدل ع...'
  - ['distance', 'ville'] : 5.04%
  - ['type', 'population'] : 7.27%
  - ['esthétique', 'ville'] : 3.69%
  - ['histoire', 'ville', 'toponymie'] : 2.71%
  - ['périphérie', 'ville'] : 3.65%
  - ['porte', 'ville'] : 3.46%
  - ['voirie', 'ville'] : 9.45%
  - ['pouvoir', 'ville'] : 3.04%
  - ['palais', 'citadelle', 'chateau'] : 4.70%
  - ['mur', 'murailles'] : 4.38%
  - ['matériaux', 'ville'] : 2.94%
  - ['service', 'ville', 'infrastructure'] : 5.93%

Chunk 38: 'صف منها لا يزيد على مايتي رجل وبالمدينة من المساجد وفي الخالصة والحارة المحيطة بها من ورا ذلك سور به...'
  - ['distance', 'ville'] : 11.51%
  - ['type', 'population'] : 12.95%
  - ['esthétique', 'ville'] : 6.90%
  - ['histoire', 'ville', 'toponymie'] : 5.53%
  - ['périphérie', 'ville'] : 5.52%
  - ['porte', 'ville'] : 6.60%
  - ['voirie', 'ville'] : 11.87%
  - ['pouvoir', 'ville'] : 6.68%
  - ['palais', 'citadelle', 'chateau'] : 6.42%
  - ['mur', 'murailles'] : 8.94%
  - ['matériaux', 'ville'] : 4.97%
  - ['service', 'ville', 'infrastructure'] : 8.25%

Chunk 39: '1 كانت متصلة بالاقرب فالاقرب منها على الوادي المعروف بوادي عباس مجاورة للموضع المعروف بالمعسكر في ضم...'
  - ['distance', 'ville'] : 7.71%
  - ['type', 'population'] : 9.41%
  - ['esthétique', 'ville'] : 3.64%
  - ['histoire', 'ville', 'toponymie'] : 5.20%
  - ['périphérie', 'ville'] : 8.33%
  - ['porte', 'ville'] : 13.15%

In [14]:
df_chunks.loc[536, 'CHUNK_MOTS']

' nota, quam cito aqua in decrescendo transit, ubicunque terra apparet, ibi statim rusticus aratrum figit et semen mittit. ln martio frumentum metunt. terra illa non parit aliud frumentum nisi tnticum et hordeum pulcherrimum omne genus leguminis a festo s.'

## **2.3. Mistral AI**

In [4]:
# Chargement de la clé API et paramètrage
MISTRAL_API_KEY = os.getenv('MISTRAL_API_KEY')
client = Mistral(api_key=MISTRAL_API_KEY)

In [7]:
# Appliquez la fonction classify avec un délai entre chaque appel
for index, row in df_chunks.iterrows():
    if index > 0 and index % 10 == 0:  # Ajoutez un délai toutes les 10 lignes, par exemple
        time.sleep(20)  # Attendez 60 secondes
    df_chunks.at[index, 'THEMES'] = classify(text_chunk=row['CHUNK_MOTS'], themes=themes, client=client)

Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...
Rate limit exceeded. Retrying in 1 seconds...

In [ ]:
# Tri des auteurs par ordre chronologique
# Nettoyer les noms d'auteurs (enlever les espaces superflus et convertir en majuscules)
df_chunks['AUTEUR'] = df_chunks['AUTEUR'].str.strip().str.upper()

ordre_chronologique = [
    "AL YAQUBI", "IBN RUSTAH", "AL-MASUDI", "IBN HAWQAL", "AL-MUQADDASI",
    "NAṢIR-I KHUSRAW", "ABU HAMID AL-GHARNATI", "AL-IDRISI", "HUGUES FALCAND",
    "GERARDUS BURCHARDUS", "BENJAMIN DE TUDELE", "GAUILLAUME DE TYR", "IBN JUBAYR",
    "THETMAR", "JACQUES DE VITRY", "OLIVIER", "VINCENT DE BEAUVAIS",
    "IBN SAID", "AL-HIMYARI"
]

# Ajuster les noms incorrects dans df_chunks si nécessaire
adjustments = {
    "NASIR-I KHOSRWO": "NAṢIR-I KHUSRAW", 
    "AL GHARNATI": "ABU HAMID AL-GHARNATI",
    "GUILLAUME DE TYR": "GAUILLAUME DE TYR",  # Ajustement de l'orthographe, si nécessaire
    "IBN  RUSTAH": "IBN RUSTAH"  # Suppression des espaces supplémentaires
}

# Appliquer les ajustements
df_chunks['AUTEUR'] = df_chunks['AUTEUR'].replace(adjustments)

# Fonction pour obtenir l'index dans ordre_chronologique, en gérant les valeurs manquantes
def get_order(auteur):
    try:
        return ordre_chronologique.index(auteur)
    except ValueError:
        # Si l'auteur n'est pas dans la liste, on lui donne un ordre arbitraire (par exemple, à la fin)
        return len(ordre_chronologique)

# Appliquer la fonction à la colonne 'AUTEUR'
df_chunks['ORDRE'] = df_chunks['AUTEUR'].apply(get_order)

# Trier le DataFrame selon l'ordre
df_chunks = df_chunks.sort_values('ORDRE').drop(columns=['ORDRE'])

In [27]:
# Sauvegarde du dataframe
df_chunks.to_excel("data/df_chunks_part2.xlsx", index=False)  # Sauvegarder df_chunks

## Premières analyses

In [31]:
df_chunks.head(5)                                   # Afficher df_chunks

,AUTEUR,LANGUE,VILLE,CHUNK_MOTS,NB_MOTS,CHUNK_ID,THEMES
0,AL YAQUBI,arabe,Le Caire,الغسطاط تعرف بباب اليون وهو الموضع المعروف بال...,50,1,"histoire de la toponymie urbaine, porte, pouvo..."
1,AL YAQUBI,arabe,Le Caire,عمرو بن العاص مسجد جامعها ودار امارتها المعروف...,36,2,"pouvoir, palais ; citadelle et château, marché..."
2,AL YAQUBI,arabe,Le Caire,واسكنه قوما وكتب الى عمر بن الخطاب بذلك فكتب ا...,50,3,"pouvoir, habitation et maison, richesse de la ..."
3,AL YAQUBI,arabe,Le Caire,لان لكل كورة مدينة مخصوصة بأمر من الامور من مد...,56,4,"histoire de la toponymie urbaine, artisanat, r..."
4,AL YAQUBI,arabe,Le Caire,ومدينة القيس وبها تعل الثياب القيسية والأكسية ...,50,5,"histoire de la toponymie urbaine, artisanat, e..."

In [32]:
x = 553
print(df_chunks.iloc[x, 3])
print(df_chunks.iloc[x, -1])

والحمرة بخطوط قبيحة مختلفة من كتب فقراء العامة إلا أن مع هذا كله على الجامع المذكور من الرونق, وحسن القبول, وانبساط النفس, ما لا تجده في جامع إشبيلية مع زخرفته, والبستان الذي في صحنه, وقد تأملت ما وجدت فيه من الارتياح والأنس دون منظر يوجب ذلك فعلمت أنه سر مودع
mosquée, jardin, richesse de la ville ou du prince

> **Traduction du passage :** Les nôtres, quand ils s'en revinrent de cette expédition, nous affirmèrent que, jamais, en terrain plat, ils n'avaient vu une citadelle plus puissante; elle possède sept tours très fortes et couvertes en dôme; en outre, sur tout son pourtour, elle est ceinte d'un double fossé, et chacun de ses fossés est défendu pat un mur ; en plus, elle possède un avant-mur.

In [33]:
# Nettoyage : transformation des chaînes de thèmes en listes
df_chunks['THEMES'] = df_chunks['THEMES'].str.split(',\s*')

# Pour chaque thème, créer une colonne avec True/False
for theme in themes:
    df_chunks[theme] = df_chunks['THEMES'].apply(lambda x: theme in x)

#Supprimer la colonne d’origine
df_chunks = df_chunks.drop(columns=['THEMES'])

# Affichage pour vérification
df_chunks.head(5)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/var/folders/7m/x2ckvpzs0zg0lkkmq5_x00g00000gn/T/ipykernel_7217/2803523237.py:2: SyntaxWarning: invalid escape sequence '\s'
  df_chunks['THEMES'] = df_chunks['THEMES'].str.split(',\s*')

,AUTEUR,LANGUE,VILLE,CHUNK_MOTS,NB_MOTS,CHUNK_ID,distance avec les autres villes,types de population,esthétique de la ville,histoire de la toponymie urbaine,...,mosquée,église,synagogue,cimetière et tombes,monuments et vestiges,pyramide,jardin,climat,animaux,plantes et arbres
0,AL YAQUBI,arabe,Le Caire,الغسطاط تعرف بباب اليون وهو الموضع المعروف بال...,50,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,AL YAQUBI,arabe,Le Caire,عمرو بن العاص مسجد جامعها ودار امارتها المعروف...,36,2,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,AL YAQUBI,arabe,Le Caire,واسكنه قوما وكتب الى عمر بن الخطاب بذلك فكتب ا...,50,3,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,AL YAQUBI,arabe,Le Caire,لان لكل كورة مدينة مخصوصة بأمر من الامور من مد...,56,4,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,AL YAQUBI,arabe,Le Caire,ومدينة القيس وبها تعل الثياب القيسية والأكسية ...,50,5,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True

In [34]:
df_chunks.shape

(609, 38)

In [35]:
cols_to_analyze = df_chunks.columns[6:]

# Compter les True et False pour chaque colonne
true_false_counts = {}
for col in cols_to_analyze:
  true_count = df_chunks[col].sum()
  false_count = (~df_chunks[col]).sum()
  true_false_counts[col] = {'True': true_count, 'False': false_count}

# Créer un DataFrame à partir des résultats
df_true_false = pd.DataFrame.from_dict(true_false_counts, orient='index')

# Afficher le DataFrame
df_true_false

                                   True  False
distance avec les autres villes      34    575
types de population                  48    561
esthétique de la ville               54    555
histoire de la toponymie urbaine     60    549
élement géomorphologique             73    536
périphérie de ville                  46    563
porte                                42    567
voirie                               20    589
pouvoir                             167    442
palais ; citadelle et château        78    531
mur et murailles                     59    550
matériaux                           105    504
infrastructure de services           32    577
eau potable et fontaine             126    483
pont                                 24    585
port et bateau                       74    535
habitation et maison                 79    530
marché                               65    544
richesse de la ville ou du prince   188    421
impôts et taxes                      33    576
espaces agricoles                    47    562
artisanat                            49    560
mosquée                             158    451
église                               26    583
synagogue                             5    604
cimetière et tombes                  38    571
monuments et vestiges                70    539
pyramide                              9    600
jardin                               39    570
climat                               28    581
animaux                              65    544
plantes et arbres                    59    550

In [36]:
df_chunks.to_excel('data/df_chunks_part2_detailed.xlsx', index=False)